### ISSUE TITLE
SuperView ERROR: open x.pgm: read-only file system

### ISSUE THREAD

**Issue by bleublancheprods** [KonradIT/gopro-linux#31]
![SuperView](https://user-images.githubusercontent.com/86064889/122419686-63668900-cf8b-11eb-880d-80576be17037.png)
Hi I got this message anyone can help me please ?
MacOS Mojave 10.14.6

**Comment by KonradIT** [comment]
This is not related to gopro-linux but rather [superview](https://github.com/Niek/superview)
