### ISSUE TITLE
Fisheye command is not compatible with GoPro Hero 5

### ISSUE THREAD

**Issue by StianOby** [KonradIT/gopro-linux#8]
The fisheye command does not successfully de-fisheye GoPro Hero 5 Black images. It seems as if the function "bends the image too far", so that there is an inverse fisheye effect. I tried finding the correct parameters for mogrify for Hero 5, through with no success as of yet. But I thought it might be useful for you to be aware of the issue.

**Comment by KonradIT** [comment]
Yes I am working on defisheye for all aspect ratios and FOVs.

**Comment by KonradIT** [comment]
Try now.

**Comment by KonradIT** [comment]
https://github.com/KonradIT/gopro-linux/commit/d21c542c0e32c29b22f37b8f0e33c89d5090e58a
